export default {
  'flash sales': [
    'skuName',
    'skuOldPrice',
    'skuNewPrice',
    'skuUnits',
    'skuTime',
    'skuImage',
    'skuStatus',
    'skuContainerId'
  ],
  'treasure hunt': [
    'skuName',
    'skuOldPrice',
    'skuNewPrice',
    'skuUnits',
    'skuTime',
    'skuImage',
    'skuStatus',
    'skuContainerId',
    'skuCategoryName',
    'skuLink',
    'skuDeepLink'
  ],
  'vouchers': [
    'skuName',
    'skuImage',
    'skuLink',
    'skuDeepLink',
    'skuId',
    'skuCode',
    'skuAppOnly',
    'skuStatus',
    'skuMinBasket',
    'skuValidity',
    'skuDiscount',
    'skuMaxDiscountAmt'
  ],
  fsSkus: [
    {
      "skuName": "Mama's Pride Rice 50kg",
      "skuOldPrice": "18500",
      "skuNewPrice": "10990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "00:00",
      "skuImage": "mamas-pride.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Gionee S10 Lite 4/32GB",
      "skuOldPrice": "42990",
      "skuNewPrice": "29990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "00:00",
      "skuImage": "gionee-s10-lite.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Nokia X5 3/32GB",
      "skuOldPrice": "54990",
      "skuNewPrice": "39990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "00:00",
      "skuImage": "nokia-x5.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Binatone Washer 4.6kg",
      "skuOldPrice": "29990",
      "skuNewPrice": "19990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "00:00",
      "skuImage": "binatone-washer.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Hisense Soundbar",
      "skuOldPrice": "22900",
      "skuNewPrice": "15990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "10:00",
      "skuImage": "hisense-sound-bar.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Looka HD TV 32\"",
      "skuOldPrice": "40300",
      "skuNewPrice": "29990",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "10:00",
      "skuImage": "looka-32-inches-tv.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Nexus Microwave 20ltrs",
      "skuOldPrice": "21000",
      "skuNewPrice": "15990",
      "skuUnits": "50",
      "skuDate": "2019-04-08",
      "skuTime": "15:00",
      "skuImage": "nexus-20-ltrs-microwave.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Binatone Dry Iron",
      "skuOldPrice": "3490",
      "skuNewPrice": "1490",
      "skuUnits": "100",
      "skuDate": "2019-04-08",
      "skuTime": "15:00",
      "skuImage": "binatone-dry-iron.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-1",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Tronsmart Speaker 25W",
      "skuOldPrice": "25900",
      "skuNewPrice": "13990",
      "skuUnits": "50",
      "skuDate": "2019-04-09",
      "skuTime": "10:00",
      "skuImage": "tronsmart-bluetooth-speaker.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-2",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "King's Cooking Oil 5ltrs",
      "skuOldPrice": "3890",
      "skuNewPrice": "1990",
      "skuUnits": "100",
      "skuDate": "2019-04-09",
      "skuTime": "10:00",
      "skuImage": "kings-vegetable-oil.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-2",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Minifocus Watch",
      "skuOldPrice": "",
      "skuNewPrice": "990",
      "skuUnits": "500",
      "skuDate": "2019-04-09",
      "skuTime": "15:00",
      "skuImage": "minifocus-watch.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-2",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Minifocus Watch",
      "skuOldPrice": "",
      "skuNewPrice": "990",
      "skuUnits": "500",
      "skuDate": "2019-04-09",
      "skuTime": "15:00",
      "skuImage": "minifocus-watch.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-2",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Nexus Washer 4.5kg",
      "skuOldPrice": "25000",
      "skuNewPrice": "15990",
      "skuUnits": "100",
      "skuDate": "2019-04-10",
      "skuTime": "10:00",
      "skuImage": "nexus-washer.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-3",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Nexus A/C 1.5HP",
      "skuOldPrice": "90000",
      "skuNewPrice": "71990",
      "skuUnits": "100",
      "skuDate": "2019-04-10",
      "skuTime": "10:00",
      "skuImage": "nexus-air-conditioner.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-3",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Binatone Standing Fan 16\"",
      "skuOldPrice": "9500",
      "skuNewPrice": "6990",
      "skuUnits": "100",
      "skuDate": "2019-04-10",
      "skuTime": "15:00",
      "skuImage": "binatone-16-inches-fan.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-3",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Binatone Blender",
      "skuOldPrice": "12000",
      "skuNewPrice": "6990",
      "skuUnits": "100",
      "skuDate": "2019-04-10",
      "skuTime": "15:00",
      "skuImage": "binatone-blender.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-3",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Tecno Spark 2 1/16GB",
      "skuOldPrice": "47500",
      "skuNewPrice": "27990",
      "skuUnits": "100",
      "skuDate": "2019-04-11",
      "skuTime": "10:00",
      "skuImage": "tecno-spark-2.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-4",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Zealot Bluetooth Speaker",
      "skuOldPrice": "7000",
      "skuNewPrice": "2990",
      "skuUnits": "100",
      "skuDate": "2019-04-11",
      "skuTime": "10:00",
      "skuImage": "zealot-bluetooth-speaker.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-4",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Molfix Baby Wipe 60 (x3)",
      "skuOldPrice": "1500",
      "skuNewPrice": "600",
      "skuUnits": "100",
      "skuDate": "2019-04-11",
      "skuTime": "15:00",
      "skuImage": "baby-wipe.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-4",
      "type": "sku",
      "tab": "0"
    },
    {
      "skuName": "Indomie Noodles 120g x40",
      "skuOldPrice": "4200",
      "skuNewPrice": "2890",
      "skuUnits": "100",
      "skuDate": "2019-04-11",
      "skuTime": "15:00",
      "skuImage": "indomie-super-pack.jpg",
      "skuStatus": "available",
      "skuContainerId": "fs-row-containers-4",
      "type": "sku",
      "tab": "0"
    }
  ],
  tab: [
    { name: 'month', field: 'select', options: [
      'jan', 'feb', 'mar', 'apr', 'may', 'jun',
      'jul', 'aug', 'sep', 'oct', 'nov', 'dec'
    ]},
    { name: 'date', field: 'input', type: 'number' },
    { name: 'day', field: 'select', options: [
      'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'
    ]}
  ],
  sku: [
    { name: 'skuDate', field: 'input', type: 'date' },
    { name: 'skuTime', field: 'input', type: 'time' },
    { name: 'skuName', field: 'input', type: 'text' },
    { name: 'skuImage', field: 'input', type: 'file' },
    { name: 'skuUnits', field: 'input', type: 'number' },
    { name: 'skuNewPrice', field: 'input', type: 'number' },
    { name: 'skuOldPrice', field: 'input', type: 'number' }
  ],
  fsTerms: [
    {
      text: "for everything you need to know about jumia's flash sales,",
      cta: 'click here',
      terms: [
        'Selected products are offered to the public at highly subsidized prices by Jumia. Discount level can be as high as 90% off depending on the offer',
        'The number of products are of a limited quantity.',
        'Flash sales go live at a specified time.',
        'Flash sales are only available on the Jumia App.',
        'Flash sales are usually limited to one item per customer.',
        'As selected products are popular and of limited quantity, you can expect them to sell out very quickly.',
        'Flash sales typically sell out in seconds.',
        'Finding an item and adding it to your cart is no guaranty that you will be able to checkout with it before others.',
        'Bear in mind that tens of thousands of people are on the same page trying to buy the same product.',
        'It’s really a case of the fastest fingers first.',
        'You need to be super quick with your phone and on a fast and stable internet connection to buy a flash sale.',
        'Jumia reserves the right to cancel orders it deems as fraudulent.',
        'Jumia reserves the right to change products offered for flash sales.'
      ]
    }
  ],
  terms: [
    { name: 'cta', field: 'input', type: 'text' }
  ],
  removedTab: [],
  months: [
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November',
    'December'
  ]
}